[package]
name = "certifica-2-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.certifica-2]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.58.0"
default-features = false
